### ISSUE TITLE
buhin arrived!

### ISSUE THREAD

**Issue by takedafutoshi** [KanazawaIoT/kanazawaiot.github.io#2]
相羽さん
加藤さん

マルツに部品が届いたようです。
いつでもお越しくださいとのことです。

竹田

**Comment by izawa** [comment]
おふたりに、追加で買い物をしていただきたく。
TWE-LITE-R というファーム書き込み用のライタが必要です。すみませんリストから漏れていました。
http://www.marutsu.co.jp/pc/i/227318/
(上記リンクは組み立てキットですが、完成品も販売されていると思います)

**Comment by PharaohKJ** [comment]
本日、お買上げしましたが、 TWE-LITE-R  売り切れ。 @izawa 貸してくださいねー。

**Comment by kitamaru** [comment]
お世話になります。

すみません、実は「TWE-LITE-R」の完成版ですが、メーカー欠品中で
現在在庫がない状況です。

入荷次第、入荷次第改めてご連絡でもよろしいでしょうか？

宜しくお願い致します。
マルツ金沢西インター店
北河

**Comment by izawa** [comment]
明日加藤さんと会うので、とりあえず持っていきます。

**Comment by izawa** [comment]
@kitamaru さん。はい、よろしくおねがいしますー。
