### ISSUE TITLE
ブログマガジンのローテーションを決定

### ISSUE THREAD

**Issue by PharaohKJ** [KanazawaIoT/kanazawaiot.github.io#4]
の週 | 担当者 | 済
---|-------|---
4/8  | @PharaohKJ | ✓
4/15 | @izawa  | ✓ 
4/22 | @takedafutoshi  | ✓
4/29 | @aibax  | ✓
5/6 | @PharaohKJ |✓
5/13 | @izawa  | ✓
5/20 | @takedafutoshi | ✓
5/27 | @aibax  | ✓
6/3 | @PharaohKJ | ✓
6/10 | @izawa  | ✓
6/17 | @takedafutoshi | ✓
6/24 | @aibax  | ✓

いったん3ヶ月実施、つまり、6月いっぱいまでやったら反省会しましょう。

**Comment by izawa** [comment]
4/15 izawa分 投稿しました。

**Comment by PharaohKJ** [comment]
@takedafutoshi さんの4/22週のを確認
@aibax さん4/29週（今週）分をお願いします。

**Comment by PharaohKJ** [comment]
@takedafutoshi さん、今週分よろしくです！

**Comment by PharaohKJ** [comment]
@aibax さん、来週よろしくです！

**Comment by PharaohKJ** [comment]
今週分がんばります。
いったん3ヶ月実施、つまり、6月いっぱいまでやったら反省会しましょう。

**Comment by PharaohKJ** [comment]
@izawa さん、今週よろしくおねがいいたします。

**Comment by PharaohKJ** [comment]
@takedafutoshi さん、今週よろしくおねがいします。
